import archiver from "archiver";
import { execFile } from "node:child_process";
import { mkdtemp, rm, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { promisify } from "node:util";
import type { CompiledSite } from "./ast-to-code.js";

const execFileAsync = promisify(execFile);

export interface ZipExportResult {
  stream: NodeJS.ReadableStream;
  filename: string;
}

export function compiledSiteFiles(site: CompiledSite): Array<{ name: string; content: string }> {
  const files: Array<{ name: string; content: string }> = [
    { name: "index.html", content: site.html },
    { name: "styles.css", content: site.css },
    { name: "Page.tsx", content: site.react },
    {
      name: "README.md",
      content: `# ${site.scope}\n\nGenerated by PQC Website IDE from a hybrid PQC-verified AST.\n`,
    },
    {
      name: "robots.txt",
      content: site.robotsTxt ?? "User-agent: *\nAllow: /\n",
    },
    {
      name: "sitemap.xml",
      content:
        site.sitemapXml ??
        `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>\n`,
    },
  ];
  if (site.demoScript) {
    files.push({ name: "demo-app.js", content: site.demoScript });
  }
  return files;
}

/** Package compiled assets into a downloadable ZIP (streaming). */
export function createZipExportStream(
  site: CompiledSite,
  projectName: string
): ZipExportResult {
  const archive = archiver("zip", { zlib: { level: 9 } });
  const safeName = projectName.replace(/[^a-z0-9]/gi, "-").toLowerCase() || "site";

  for (const file of compiledSiteFiles(site)) {
    archive.append(file.content, { name: file.name });
  }

  void archive.finalize();

  return {
    stream: archive,
    filename: `${safeName}.zip`,
  };
}

export interface GitOpsPushOptions {
  remoteUrl: string;
  branch: string;
  commitMessage: string;
  authorName: string;
  authorEmail: string;
  /** Bearer token or deploy key for HTTPS remote (never logged). */
  credentials?: string;
}

/** Path segments exclude `/` so the group cannot backtrack exponentially (S5852). */
const ALLOWED_REMOTE = /^https:\/\/[a-zA-Z0-9._-]+(?:\/[a-zA-Z0-9._-]+)+\/?$/;

export class GitOpsError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "GitOpsError";
  }
}

export function validateGitRemote(url: string): void {
  if (!ALLOWED_REMOTE.test(url)) {
    throw new GitOpsError("Only HTTPS git remotes are allowed");
  }
  if (/[@\s]/.test(url.split("://")[1] ?? "")) {
    throw new GitOpsError("Credentials must not be embedded in remote URL");
  }
}

/**
 * GitOps flow: write compiled files to a temp repo, commit, push to secure HTTPS remote.
 * Requires `git` CLI on the host.
 */
export async function pushCompiledSiteToGit(
  site: CompiledSite,
  options: GitOpsPushOptions
): Promise<{ branch: string; commitMessage: string }> {
  validateGitRemote(options.remoteUrl);

  const workDir = await mkdtemp(join(tmpdir(), "pqc-gitops-"));
  try {
    await execFileAsync("git", ["init"], { cwd: workDir });
    await execFileAsync("git", ["checkout", "-b", options.branch], { cwd: workDir });

    for (const file of compiledSiteFiles(site)) {
      const filePath = join(workDir, file.name);
      await mkdir(dirname(filePath), { recursive: true });
      await writeFile(filePath, file.content, "utf8");
    }

    await execFileAsync("git", ["add", "-A"], { cwd: workDir });
    await execFileAsync(
      "git",
      [
        "-c",
        `user.name=${options.authorName}`,
        "-c",
        `user.email=${options.authorEmail}`,
        "commit",
        "-m",
        options.commitMessage,
        "--allow-empty",
      ],
      { cwd: workDir }
    );

    const pushUrl = withCredentials(options.remoteUrl, options.credentials);
    await execFileAsync("git", ["push", pushUrl, `HEAD:${options.branch}`], {
      cwd: workDir,
      env: { ...process.env, GIT_TERMINAL_PROMPT: "0" },
    });

    return { branch: options.branch, commitMessage: options.commitMessage };
  } finally {
    await rm(workDir, { recursive: true, force: true });
  }
}

function withCredentials(httpsUrl: string, token?: string): string {
  if (!token) return httpsUrl;
  const u = new URL(httpsUrl);
  u.username = "oauth2";
  u.password = token;
  return u.toString();
}
